apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-staging
resources:
  - ../../base/guestbook
patchesStrategicMerge:
  - replica-patch.yaml
commonLabels:
  environment: staging
