apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
commonLabels:
  app.kubernetes.io/name: guestbook
  app.kubernetes.io/component: frontend
images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.2"
