apiVersion: apps/v1
kind: Deployment
metadata:
    name: guestbook-ui
spec:
  template:
    spec:
      containers:
        - name: guestbook-ui  
          image: gcr.io/heptio-images/ks-guestbook-demo:nonexistent-tag
