apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook-dev
resources:
  - ../../base/guestbook
  - configmap.yaml
patchesStrategicMerge:
  - replica-patch.yaml
  #- image-patch.yaml
commonLabels:
  environment: dev
